### ISSUE TITLE
高版本sdk不能用吗？

### ISSUE THREAD

**Issue by kdsrsl** [xujianhui404/PluginAppDemo#3]
Plugin Main Activity setContenxtView(int)，资源找不到

android.content.res.Resources$NotFoundException: Resource ID #0x7f0d0000

谢谢.

**Comment by kaina404** [comment]
??

**Comment by kdsrsl** [comment]
我把代码应用在sdk 28上，可以找到 PluginMainActivity,但是运行到这个Activity的setContextView(R.id.activity_main)时，崩溃，提示找不到资源。

**Comment by kaina404** [comment]
你看下R文件是否导入错误或者是否有activity_main.xml文件

**Comment by kdsrsl** [comment]
包里有activity_main.xml，怀疑是R文件导入问题，但是6.0环境正常，高版本不行，奇怪。。。。

**Comment by kaina404** [comment]
.....

**Comment by kdsrsl** [comment]
刚刚又试了一下，把库直接clone下来，然后配置 28，28.0.3，28.0.0。编译后，果然还是一样的问题啊

load时 报 
```
06-27 17:32:16.134 21101-21101/xu.pluginappdemo E/u.pluginappdem: Invalid ID 0x00000000.
```
然后 打开时，崩溃
```
06-27 17:33:33.657 21101-21101/xu.pluginappdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xu.pluginappdemo, PID: 21101
    java.lang.NullPointerException: Attempt to invoke interface method 'void xu.plugin.PluginInterface.onStart()' on a null object reference
        at xu.pluginappdemo.Plugin.ProxyActivity.onStart(ProxyActivity.java:62)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
        at android.app.Activity.performStart(Activity.java:7252)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2970)
```

所以这个方案是不能向后兼容吗？

@kaina404
